package com.it.openmechanic.utils

const val SHARED_PREFERENCES_NAME = "OPEN_MECHANIC_SHARED_PREFERENCES"
const val SMS_EXPIRED_ERROR = "ERROR_SESSION_EXPIRED"
const val SMS_INVALID_CODE_ERROR = "ERROR_INVALID_VERIFICATION_CODE"